@startuml

skinparam TitleFontSize 16
title "Mediator Pattern UML Diagram"

class User {
    #mediator : ChatMediator
    #name: string
    +User(in mediator: ChatMediator, in name: string)
    +send(in message: string) : void
    +receive(in message: string) : void
}

interface ChatMediator {
    +add_user(in user: User): void
    +send_message(in message: string, in sender: User): void
}

class ChatRoom {
    -users : vector<User>
    +add_user(in user: User): void
    +send_message(in message: string, in sender: User) : void
}

User o-- ChatMediator
ChatRoom o-- User
ChatRoom <|-- ChatMediator

@enduml
